### ISSUE TITLE
Ingredients Screen Food Assets -- Khayree

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#111]
Create assets of food for the ingredients selection screen. 

Priority Concepting

- Peculiar Peppers
- Ground Beef
- Onions
- Whipped Cream
- Cheese

Needs Lines
- Aquarium Gravel
- Ice Cream
- Grated Souls
- Canned Meat
- Canned Beans
- Grated Souls

**Comment by gmarino2048** [comment]
@Aideryn can you close this out if it's done
