### ISSUE TITLE
Ingredients Screen Food Assets -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#112]
Needs Lines and Colouring
- Bones
- Eggs (whole)
- Algae Slime
- Void Goo
- Weird Steak

**Comment by Farren183** [comment]
https://github.com/gmarino2048/AGD_Project/blob/master/Art/Food_Assets/PNGs/Mazur_Bones_1.png
https://github.com/gmarino2048/AGD_Project/blob/master/Art/Food_Assets/PNGs/Mazur_Eggs_1.png
https://github.com/gmarino2048/AGD_Project/blob/master/Art/Food_Assets/PNGs/Mazur_VoidGoo_1.png
https://github.com/gmarino2048/AGD_Project/blob/master/Art/Food_Assets/PNGs/Mazur_WeirdSteak_1.png

https://github.com/gmarino2048/AGD_Project/blob/master/Art/UXUI/PNG/Mazur_MainMenu_Instructions_2.png
https://github.com/gmarino2048/AGD_Project/blob/master/Art/UXUI/PNG/Mazur_MainMenu_Credits_2.png
