### ISSUE TITLE
Finish Menu Details -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#113]
Create Changes for Menus

Main Menu
- Quit Button

Options Menu
- Assets exported in separate parts

Credits Menu
- Add peoples names and roles

Instructions Menu
- Write instructions and concept out layouts

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/46585586-a9c86380-ca40-11e8-80b7-9adb552335cb.png)

![image](https://user-images.githubusercontent.com/42968997/46585590-b51b8f00-ca40-11e8-9ec0-6efe57790d88.png)
