### ISSUE TITLE
Tutorial Animations -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#114]
Create Tutorial Animations for the following minigames using assets provided by Bailey.

Mixing
- Mouse grabs spoon and moves in circular motion.

Grill
- Mouse places food on grill, (move mouse away from food) over time sprite darkens, then click on food when done triggering spatula to go in and flip it away. Toss that bitch into the void or smth idk.

**Comment by TheNamesAshli** [comment]
![hudson_tutgrill_1](https://user-images.githubusercontent.com/42968973/46574610-f1cd8480-c973-11e8-8293-a51c24a675dd.gif)
![hudson_tutstir](https://user-images.githubusercontent.com/42968973/46574611-f1cd8480-c973-11e8-9b60-4bdd3c5b45f9.gif)
