### ISSUE TITLE
Minigame BG Renders Pt. 2 Electric Boogaloo -- Pam

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#115]
Finish up backgrounds for

- Mixing Minigame
- Grill Minigame

Upload without placeholder assets

**Comment by SmallestPamcakes** [comment]
![pizarro-ruiz_mixingbg_3](https://user-images.githubusercontent.com/42968970/46567411-a0d07880-c900-11e8-8208-ce5362457319.png)
![pizarro-ruiz_grillbg_2](https://user-images.githubusercontent.com/42968970/46567418-aded6780-c900-11e8-8966-602e06c6176a.png)
