### ISSUE TITLE
Cerberus' Sketches -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#134]
Create sketches for Cerberus' Sprites. If digital, should be no bigger than 700x850 per sprite. Combat sprites can be as long as 1700 but still no taller than 850. Sketches should include the full body of the sprite unless there is no bodily reaction from the monster to go with the mood change. (I would strongly suggest having one though)

DIALOGUE
- Neutral Expression, Default
- Negative Expression, (Bad Dialogue Response)
- Positive Expression, (Good Dialogue Response)

COMBAT
- Default Pissed
- Damaged (Hit Reaction)
- Attacking (Swipe at Player)

**Comment by TheNamesAshli** [comment]
![hudson_cerbangered_1](https://user-images.githubusercontent.com/42968973/46747604-c1415f80-cc7f-11e8-8df2-5a7c5b3c5800.png)
![hudson_cerbdamaged](https://user-images.githubusercontent.com/42968973/46747606-c1415f80-cc7f-11e8-8a8b-1fdac89028fd.png)
![hudson_cerbdefault_1](https://user-images.githubusercontent.com/42968973/46747608-c1415f80-cc7f-11e8-8a16-8d33c86279c3.png)
![hudson_cerbnegative_1](https://user-images.githubusercontent.com/42968973/46747610-c1d9f600-cc7f-11e8-9782-d9f2395f0ec0.png)
![hudson_cerbpositive_1](https://user-images.githubusercontent.com/42968973/46747611-c1d9f600-cc7f-11e8-9d58-40822733e434.png)
![hudson_cerbswipe_1](https://user-images.githubusercontent.com/42968973/46747612-c1d9f600-cc7f-11e8-93ed-2821e9df19f5.png)
