### ISSUE TITLE
Minigame Animations -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#142]
Create animations for ingredient assets during minigames. Things that are in **Bold** are the priority and should be focused on during the first week (by the 14th) 

Mixing
- **Spoon going around the bowl - Clockwise (Should have lines to show liquid being mixed on a separate layer)**
- **Spoon going around the bowl - Counter clockwise (Should have lines to show liquid being mixed on a separate layer)**
- **Mixing Asset (Circular Sprite) Rotating at a slightly slower speed than spoon (this should be a 100% symbol animation)** 

Chopping
- Knife swinging down quickly and returning to same position (Flick animation)

Shaking
- Sprinkles of "food" being dispensed from Item (this is just the sprinkles, no object attached) Should be in singular 'puffs'
**- Aquarium Gravel Sprinkles**
- Crushed Souls Sprinkles
 
Grilling
- Cooking Sprite for Steak (Steadily Darkens until it reaches a "Cooked State"
- Cooking Sprite for Ground Beef (Steadily Darkens until it reaches a "Cooked State"

Microwave
- Food Items cooking & spinning in the microwave (Animation should last 10 seconds (loops are fine for most of the time, but towards the end, cans should start shaking and being erratic)
- Can O Beans (rotated)
- Can of meat (rotated)
**- Algae Slime (should like, bubble & melt or smth, its essentially jello in a microwave)**

**Comment by TheNamesAshli** [comment]
[There's gonna be a lot of .gifs here, oh boy. Any versions of the mixing animations, there is a Counter Clockwise version, I just didn't make gifs of them but they are  available in sprite sheet form.]

Cooking Sprite for Weird Steak
![hudson_minigrill_weirdsteak_1](https://user-images.githubusercontent.com/42968973/47303073-0905a680-d5f1-11e8-9c87-0cc3a90c834d.gif)

Eggs combined
![hudson_minimixeggcombined_1](https://user-images.githubusercontent.com/42968973/47303074-0905a680-d5f1-11e8-9a70-50835ced81ca.gif)

Eggs Separated
![hudson_minimixeggseparated_1](https://user-images.githubusercontent.com/42968973/47303075-0905a680-d5f1-11e8-9b9d-e60a2242eed8.gif)

Egg Transition
![hudson_minimixeggtransition_1](https://user-images.githubusercontent.com/42968973/47303076-0905a680-d5f1-11e8-9203-944f57163e71.gif)

Everything included with mixing the eggs.
![hudson_minimixmaster_1](https://user-images.githubusercontent.com/42968973/47303077-0905a680-d5f1-11e8-9998-ddec07d71132.gif)

Spoon alone
![hudson_minimixspoonconstant_1](https://user-images.githubusercontent.com/42968973/47303078-099e3d00-d5f1-11e8-8371-cda52e22804f.gif)

Mixing lines fading in & Out
![hudson_minimixspoonfadein_1](https://user-images.githubusercontent.com/42968973/47303080-099e3d00-d5f1-11e8-876e-e8d10d9efe62.gif)
![hudson_minimixspoonfadeout_1](https://user-images.githubusercontent.com/42968973/47303082-099e3d00-d5f1-11e8-9cc3-5f371c1abc90.gif)

Aquarium Gravel & Crushed Souls [I need to slightly alter color for Crushed Souls to better match the sprite, but ideally it would look just like the gravel in terms of how it's animated.)
![hudson_minishake_gravel_1](https://user-images.githubusercontent.com/42968973/47303083-099e3d00-d5f1-11e8-8f58-3324a14a2edc.gif)
![hudson_minishake_souls_1](https://user-images.githubusercontent.com/42968973/47303084-099e3d00-d5f1-11e8-946b-c5d19bfc292d.gif)

**Comment by Aideryn** [comment]
Grilling ground beef

Knife chop

Spatula flip

**Comment by TheNamesAshli** [comment]
Chop (12 Frames, Longer standard version)
![hudson_minichop_knifelong_1](https://user-images.githubusercontent.com/42968973/47611060-7a02ef00-da33-11e8-8fb6-1f6e0bca0bce.gif)

Chop (8 Frames, Shorter more "flicky" version.)
![hudson_minichop_knifeshort_1](https://user-images.githubusercontent.com/42968973/47611061-7a9b8580-da33-11e8-8229-bd4913f0be4f.gif)

Beef
![hudson_minigrill_beef_1](https://user-images.githubusercontent.com/42968973/47611062-7a9b8580-da33-11e8-8a39-b8a6f3490c22.gif)

Spatula
![hudson_minigrill_spatula_1](https://user-images.githubusercontent.com/42968973/47611063-7a9b8580-da33-11e8-9752-babe82d740aa.gif)

Color corrected crushed souls.
![hudson_minishake_souls_2](https://user-images.githubusercontent.com/42968973/47611064-7a9b8580-da33-11e8-8b56-f5ee0ee3b574.gif)

**Comment by TheNamesAshli** [comment]
Addition of souls coming out of the crushed souls shaker. There is a separate sprite sheet for just the floating souls if timing needs to be adjusted.

![hudson_minishake_soulghosts_1](https://user-images.githubusercontent.com/42968973/47744031-b498a180-dc56-11e8-9127-037f5e84b18c.gif)
![hudson_minishake_crushedsouls_3](https://user-images.githubusercontent.com/42968973/47744053-c11cfa00-dc56-11e8-96f9-0437e97d86e3.gif)

**Comment by TheNamesAshli** [comment]
Microwaved beans (Canned meat looks exactly the same, so I'm not providing a .gif.)
![hudson_microwavebeans_1](https://user-images.githubusercontent.com/42968973/48034486-9a1a6880-e12d-11e8-8419-7ec9ef4f2cfb.gif)

Burned Beef
![hudson_minigrill_burnedbeef_1](https://user-images.githubusercontent.com/42968973/48034487-9a1a6880-e12d-11e8-8822-075ee642d7b5.gif)

Burned Weird Steak (I can try to smooth this transition better if requested.)
![hudson_minigrill_burnedweirdsteak_1](https://user-images.githubusercontent.com/42968973/48034488-9a1a6880-e12d-11e8-9d27-c74ce238e0f0.gif)

Microwaved Slime
![hudson_microwaveslime](https://user-images.githubusercontent.com/42968973/48034506-b5857380-e12d-11e8-8494-1a6e34c04da3.gif)

Ice Cream and Chili gifs are too large to have here, but I'll upload them to the drive.
