### ISSUE TITLE
Menu Asset PNGs -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#144]
Export all menu assets and buttons as separate PNG's so that they are able to be implemented. This includes Buttons, Backgrounds, and Slider Assets

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/47092298-bc872900-d1f4-11e8-946c-73b30762cd6a.png)

![image](https://user-images.githubusercontent.com/42968997/47092276-b133fd80-d1f4-11e8-8303-cc006566f4f7.png)

![image](https://user-images.githubusercontent.com/42968997/47092333-cc9f0880-d1f4-11e8-9350-0e0b22acf2d6.png)

![image](https://user-images.githubusercontent.com/42968997/47092372-dde81500-d1f4-11e8-8098-1b40a099ec22.png)

There are a total of 17 separate PNGs, here are a few of them
