### ISSUE TITLE
Minigame Food Assets -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#145]
Create Minigame Assets for Animation purposes

Mixing
- Create Mixing ingredient starting and ending sprite (Should be a circle shape. Literally a Shape with colour added over top)
- Egg Mixing Start (Should be like, 3 egg yokes in the bowl w the slimy stuff)
- Egg Mixing End (You know what beaten eggs look like yes? That)

Grilling
- Weird Steak needs a sprite to be used in the minigame if the one we have doesn't match the perspective. (Check that for me)
- It also needs a Cooked Sprite to match that. One that clearly shows that it is done and ready to be removed.

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/47092479-0ff97700-d1f5-11e8-8808-fa785092444f.png)

![image](https://user-images.githubusercontent.com/42968997/47092504-1a1b7580-d1f5-11e8-8e24-cea1272081eb.png)

![image](https://user-images.githubusercontent.com/42968997/47092517-21db1a00-d1f5-11e8-870d-95b3bce552d2.png)

![image](https://user-images.githubusercontent.com/42968997/47092533-2d2e4580-d1f5-11e8-821c-b6f04c916681.png)

![image](https://user-images.githubusercontent.com/42968997/47092546-34555380-d1f5-11e8-8488-7c33a4d6dc1e.png)

![image](https://user-images.githubusercontent.com/42968997/47092561-3e775200-d1f5-11e8-9346-a5966b706ee0.png)

![image](https://user-images.githubusercontent.com/42968997/47092571-446d3300-d1f5-11e8-983e-1aebb0091e73.png)
