### ISSUE TITLE
Miscellaneous Sprites -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#189]
Sorry Bailey but you got a bunch  of random work to do!

Minigame Assets
- Ground Beef Uncooked
- Ground Beef Partially Cooked
- Ground Beef Cooked
(Reference this for idea of what it should look like colour wise: https://github.com/gmarino2048/AGD_Project/blob/master/Art/Food_Assets/PNGs/GroundBeef.png )

- Spatula Asset (Needs to be more pastel and drawn in PS. Reference Grill BG for perspective)

UX/UI Stuff

- Menu BG Colour Change (the shadow on the counter needs to be warmer, not as close to a black colour.)
- Shading on Utensils (if this needs to be brought into PS to be done then feel free!)
- LineArt Colour needs to be a purply boyo. This is the Hex code for the colour I've been using #3D2E63, if you want to get pams that also works)
- Warm up some colours if they look too neutral after you do this (this is optional, I just dont know how everything will look once you've done the rest of this

-Namebox Sprite! Be sure it has enough room for [REDACTED]s name (All names should be the same font size when put on it. Love I think is fine for the font here. If you have other ideas let me know!)

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/47610266-f4754400-da1e-11e8-948a-311637700fc1.png)
![image](https://user-images.githubusercontent.com/42968997/47610264-ed4e3600-da1e-11e8-915c-a4f05260e74b.png)
![image](https://user-images.githubusercontent.com/42968997/47610260-e45d6480-da1e-11e8-8cc3-06e6a73a64a4.png)
![image](https://user-images.githubusercontent.com/42968997/47610268-0ce55e80-da1f-11e8-8b5d-86c72e7c3a7e.png)
![image](https://user-images.githubusercontent.com/42968997/47610277-30100e00-da1f-11e8-88d9-a1e978cfaef3.png)
![image](https://user-images.githubusercontent.com/42968997/47610271-1a9ae400-da1f-11e8-962c-6ed66b5f9921.png)
![image](https://user-images.githubusercontent.com/42968997/47610272-2090c500-da1f-11e8-92c9-45ed8b159684.png)
![image](https://user-images.githubusercontent.com/42968997/47610273-27b7d300-da1f-11e8-9272-73af4b4d4496.png)
