### ISSUE TITLE
Cerberus Entrance -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#214]
Create a concept and finalize a unique entrance for Cerberus. (ex. Nessie brings water, redacted has smoke appear and then pops in through the void)

Doesn't matter if its an animation or a sprite or whatever. Just do what feels right for Cerberus.

**Comment by TheNamesAshli** [comment]
Adding concepts here for convenience of previewing.

![cerbentrance_1](https://user-images.githubusercontent.com/42968973/48073281-6b8fa280-e1ac-11e8-8295-4b9864ebeaf3.png)
![cerbentrance_2](https://user-images.githubusercontent.com/42968973/48073282-6b8fa280-e1ac-11e8-8108-0c870169d696.png)
![cerbentrance_3](https://user-images.githubusercontent.com/42968973/48073284-6b8fa280-e1ac-11e8-92d8-bee34db30811.png)
![cerbentrance_4](https://user-images.githubusercontent.com/42968973/48073285-6c283900-e1ac-11e8-8a0e-48cbadf70b31.png)

**Comment by TheNamesAshli** [comment]
I promise the blank frame at the end is intentional this time.

![hudson_cerberus_entrance_1](https://user-images.githubusercontent.com/42968973/48357213-0a614680-e666-11e8-8e6e-5578526830b1.gif)
