### ISSUE TITLE
Food Sprites -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#215]
Create the Charred and Overcooked versions of the Ground Beef and Weird Steak.

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/47955130-950cbc00-df69-11e8-9c60-a7aa4a425f98.png)
![image](https://user-images.githubusercontent.com/42968997/47955136-9f2eba80-df69-11e8-9274-7f4cfe9906e4.png)
![image](https://user-images.githubusercontent.com/42968997/47955146-b077c700-df69-11e8-8ac3-33b3c6a7be0f.png)
![image](https://user-images.githubusercontent.com/42968997/47955140-a8b82280-df69-11e8-931f-a5f3286489d5.png)
