### ISSUE TITLE
Pause Menu -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#216]
Create Pause Menu Assets and Layout Example

- BG
- Volume Controls
- Back Button
- Dialogue Space (can just be empty, just needs to exist)
- Scroll bar aesthetics (Both BG Line and Scroll Clickable)
- Quit Button

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/48448002-a88b0480-e76b-11e8-86f5-d8c153e167d9.png)
