### ISSUE TITLE
Final Sound Library -- Chamar

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#219]
Sounds needed to (hopefully) finish off the sound library.

- Power switch sound (like that sound when the lights go off or on thats real heavy sounding)
- Nessie water flood sound
- Fire sound (campfire esque)
- Spooky void sound?
- Tear through reality sound?
- Diner Ambiance
- Meat Place
- Souls Sound
- Beat Eggs (Stir)
- Ice Cream Stir
- Goo Stir
- Can Banging
- Goo Bubbling
- Phone Dialing

**Comment by BigAutopsy** [comment]
Sounds Left:                                                       [M] = Mic Needed

Power switch sound
Fire sound (Stock Effect Needed)
Spooky Void
Reality Tear
Meat Place [M] (Stock Effect Needed MAYBE) 
Eggs Beat [M]
Ice Cream Stir (Ice Cream stirring too low of a sound, use sand scooping stock effect instead)
Goo Stir (Leftover Alfredo in the fridge) [M]

**Comment by BigAutopsy** [comment]
Mishon Compree
