### ISSUE TITLE
Tutorial & Scoring BG -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#250]
Tutorial and Scoring backgrounds. Make two versions, one covering the full screen the other being a centered asset. Test out different fonts for the scoring so we know which to use.

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/48447968-87c2af00-e76b-11e8-94c2-bcd5d36312a0.png)
![image](https://user-images.githubusercontent.com/42968997/48447978-8ee9bd00-e76b-11e8-81bd-403884782146.png)
