### ISSUE TITLE
Combat UI -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#251]
Create a UI Bar for both the players health and the manager meter. These should have transparent centers and fit thematically with the saturated colours of the combat scene.

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/48447897-51852f80-e76b-11e8-9f97-719c9b7ae2fc.png)
![image](https://user-images.githubusercontent.com/42968997/48447910-5d70f180-e76b-11e8-8aa2-84f5f84af6e7.png)
