### ISSUE TITLE
Combat Animations -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#254]
This a big issue Ashli I hope you're ready.

Create combat animations for all the monsters idles. you can cut and paste as you please I will go into the sprite sheet and do cleaning for the lineart and colouring. Just make em cool or w/e. Here I will list the ideas for the idle combat animations. Ill direct link to the sprite you should use nest to the name.

Nessie ( https://drive.google.com/open?id=1ugz7ETGXhU42kjSwXaYN1aKNWyqCubMw )
- Neck squiggle back and forth. give it a cool s shape thing.
- Have the lower jaw slightly move down and up. 

Cerberus ( https://drive.google.com/open?id=1aoWPFnFJJQNNZuCH_jVY-QjYA-frVFy5 )
- Crouch down a lil and go back to neutral stance
- Head bob left head first then the middle then right

[REDACTED] ( https://drive.google.com/open?id=1EKZMwzPqNQorj2oDZTMhkTqfYbCkGCwK )
- Big arms rotate at the elbow to do a lil wave. 
- Wrists on talon arms rotate. 
(if you have questions about any of these please ask!!)

**Comment by TheNamesAshli** [comment]
.gif files available in the drive since they're too large to post here.
[ https://drive.google.com/drive/u/1/folders/1StsvXEnFy4zKemYkUQStlxTIWb4Ymt70 ]

**Comment by TheNamesAshli** [comment]
![hudson_combat_cerberus_1](https://user-images.githubusercontent.com/42968973/48357846-8314d280-e667-11e8-8261-572cfb996a39.gif)
![hudson_combat_redacted_1](https://user-images.githubusercontent.com/42968973/48357848-8314d280-e667-11e8-9a27-3c120140d11a.gif)
![hudson_combat_nessie_1](https://user-images.githubusercontent.com/42968973/48357849-83ad6900-e667-11e8-981e-a0bc2b134552.gif)
