### ISSUE TITLE
PC Monologue -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#285]
Write the characters monologue for the beginning and end of the game! Doesn't need to be overly long but enough to cover all the key points!

Beginning Key Points
- Talk about job (and mention how your shift is late)
- Talk about weird customers (be somewhat vague, don't say theyre monsters)
- Talk about how maybe you can get something out of this, something like, a date??????
- Have it end w/ something to be like "here comes one now" and then  Nessie enters

End Key Points
- Something bout your shift being over
- Somethin bout goin on a date
- Hell yea

**Comment by Farren183** [comment]
https://github.com/gmarino2048/AGD_Project/blob/master/Art/Dialogue/Mazur_Intro_Monologue_1.txt?raw=true
