### ISSUE TITLE
Shaking Sprites -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#287]
Create Sprites for shaking scene! 

6 Sprites each that gather more in height as you gooooo

First one should just be an indicator that stuffs happening and 5/6th is like mountain

Draw over the linearts for the final dishes (located in the drive)

Gravel should match colouration from animation sprite, can be small pebbles

Crushed Souls should be like glittttttttttter and somewhat match the animation sprite (because theyre hitting a liquid a slight colour change is allowed,)

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/48789563-5b52e980-ecbb-11e8-9203-13a04740f970.png)
![image](https://user-images.githubusercontent.com/42968997/48789580-6279f780-ecbb-11e8-8ee4-bf72cadee35a.png)
