### ISSUE TITLE
Screen Layouts -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#33]
Layouts for button and hit locations for both the title and battle screens. These should be 1920x1080 to start but keep in mind variable sizes.

All of your files should be uploaded to git using a separate branch (Reference the CONTRIBUTION.md if you need help remembering how that works, or ask me) and the branch should then be linked to the issue it is associated with. If file size permits you can also just comment on the issue with the file attached.

**Comment by Farren183** [comment]
![mazurbattleui-01](https://user-images.githubusercontent.com/42968997/45371158-eaef6400-b5b7-11e8-8b1e-2e1333dbb599.png)
![mazurbattleuiguide](https://user-images.githubusercontent.com/42968997/45371163-ecb92780-b5b7-11e8-92a7-8d3e0c5566ec.png)
These are the layouts for the battle UI. Let me know if we need to make any changes.

**Comment by Aideryn** [comment]
Update Battle UI for new layout! (Talk/Heal Screen and Dialogue (talk option) screen, not much different but yknow)

**Comment by Farren183** [comment]
![mazurmainmenulayout-01](https://user-images.githubusercontent.com/42968997/45626560-d995d400-ba5d-11e8-9461-21f504b21fd1.png)
![mazuringameui](https://user-images.githubusercontent.com/42968997/45626561-d995d400-ba5d-11e8-9ac2-6e81ffedcd92.png)
![mazuringameuiguide](https://user-images.githubusercontent.com/42968997/45626562-d995d400-ba5d-11e8-804d-489dc396eb17.png)

UI Layouts

**Comment by Farren183** [comment]
![mazurmainmenuart-01](https://user-images.githubusercontent.com/42968997/45626660-0cd86300-ba5e-11e8-8b97-f8b775160524.png)
![mazuroptionsmenu-01](https://user-images.githubusercontent.com/42968997/45626662-0cd86300-ba5e-11e8-9e86-ee0160ee513e.png)
![mazurcreditsmenu-01](https://user-images.githubusercontent.com/42968997/45626663-0cd86300-ba5e-11e8-974a-68af7f0f11fd.png)
![mazurinstructionsmenu-01-01](https://user-images.githubusercontent.com/42968997/45626664-0d70f980-ba5e-11e8-8485-ce15312417d8.png)

Main Menu stuff
