### ISSUE TITLE
Combat Anim part two electric booglaloo -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#342]
Do those Combat Boys Againnnnn

For redacted and cerberus. The pull request with their puppet sprites is up!

**Comment by TheNamesAshli** [comment]
New Spicy Combat Idles! Now with delicious tweens! Smooth goodness!

![hudson_combat_redacted_2](https://user-images.githubusercontent.com/42968973/48915872-e7911800-ee45-11e8-8c59-c39ec5423046.gif)
![hudson_combat_cerberus_2](https://user-images.githubusercontent.com/42968973/48915873-e829ae80-ee45-11e8-93b6-c3fc52a01b66.gif)
