### ISSUE TITLE
Buttons and Menus -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#343]
Buttons

- Enter/Next Button for name screen
- Start Over/Return to Main Menu button for Game over Screen 

Both should be in the style of the menu but also not look out of place on the screens (aka dont put a red border one for the blue screen)

Credits and Instructions text needs updating, I'll send you a doc for that

Add section for displaying text speed w lines and such

Create Tool Tip size option
Ask the programmers if it should be a slider or numbers.

**Comment by Farren183** [comment]
![image](https://user-images.githubusercontent.com/42968997/49086508-b0927c00-f222-11e8-97ac-fbc4bd691ce8.png)
![image](https://user-images.githubusercontent.com/42968997/49086524-b8eab700-f222-11e8-9850-8b2e352dce17.png)
![image](https://user-images.githubusercontent.com/42968997/49086531-bee09800-f222-11e8-9f41-606fba1c92c7.png)
![image](https://user-images.githubusercontent.com/42968997/49086552-cacc5a00-f222-11e8-98d9-122a1cf0d0b6.png)
![image](https://user-images.githubusercontent.com/42968997/49086576-dcadfd00-f222-11e8-9163-baf96d7d86e9.png)

![image](https://user-images.githubusercontent.com/42968997/49086590-e7689200-f222-11e8-828c-9d5933210a25.png)
![image](https://user-images.githubusercontent.com/42968997/49086603-ef283680-f222-11e8-97d5-3d151ffd5988.png)
