### ISSUE TITLE
Standard Animations -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#35]
Start creating standard animations like fire starting, microwave open and close, and once base assets are created things like cooking of foods and such (Khayree is tagged in this issue for this purpose as he is making the base assets.) If you are able/if khayree needs it you can help with the creation of food assets.

These should be 1920x1080 to start but keep in mind variable sizes.

All of your files should be uploaded to git using a separate branch (Reference the CONTRIBUTION.md if you need help remembering how that works, or ask me) and the branch should then be linked to the issue it is associated with. If file size permits you can also just comment on the issue with the file attached.

**Comment by TheNamesAshli** [comment]
Microwave (Open/Close loop for previewing purposes.)
https://github.com/gmarino2048/AGD_Project/blob/Hudson_AnimFlame/Art/Hudson_Assets/Hudson_MicrowaveLoop.gif

Fire (Loop)
https://github.com/gmarino2048/AGD_Project/blob/Hudson_AnimFlame/Art/Hudson_Assets/Hudson_FlameLoop.gif

Fire (Start)
https://github.com/gmarino2048/AGD_Project/blob/Hudson_AnimFlame/Art/Hudson_Assets/Hudson_FlameStart.gif
