### ISSUE TITLE
Common Elements -- Fade to Black

### ISSUE THREAD

**Issue by gmarino2048** [gmarino2048/AGD_Project#46]
Whoever has time, please tackle this simple task. Just make the screen fade in from black and fade down to black to make transitions easier. You might want to have a layer of all black and fade the opacity, but implementation is up to you. @bazahmed @riyuezaozao I'll let you guys figure out who tackles this one.

**Comment by riyuezaozao** [comment]
Just done a prototype

**Comment by gmarino2048** [comment]
@riyuezaozao If you're done with the prototype, you can go ahead and close this issue.
