### ISSUE TITLE
Battle UX/UI -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#50]
Start creation of Battle UI. 
Assets Needed
- Talk Button (Possibly renamed)
- Dodge Button
- Heal Button
- Pause Button
- Damaged Notepad (Start with a generically damaged one, we can do monster specific later)

**Comment by Aideryn** [comment]
Test Link Comment


https://github.com/gmarino2048/AGD_Project/blob/master/Art/AI%20Files/MazurInGameUI.ai

**Comment by Farren183** [comment]
![mazuringameuiguide](https://user-images.githubusercontent.com/42968997/45626485-b408ca80-ba5d-11e8-8637-999637bade60.png)
![mazurbattleuiart-01](https://user-images.githubusercontent.com/42968997/45626486-b408ca80-ba5d-11e8-9e9c-a6bb7aa0cd77.png)
![mazuringameui](https://user-images.githubusercontent.com/42968997/45626487-b408ca80-ba5d-11e8-875f-d800e9706004.png)

Battle UI and UI layout
