### ISSUE TITLE
Soundtracks -- Chamar & Jonathan

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#58]
This issue is for the creation of soundtracks. I'm going to leave it open for 3 weeks and then we'll make new ones as needed. Here you can post beginning tracks as theyre created and discuss any changes that need to be made.

Here is a current list of tracks that we need for the game
- Dialogue/First meeting
- Battle
- Cooking

**Comment by BigAutopsy** [comment]
Check this fire hot beat yo 

https://github.com/gmarino2048/AGD_Project/tree/master/Art/Sound

**Comment by BigAutopsy** [comment]
Thisshitsucksactually.jpeg

**Comment by BigAutopsy** [comment]
Battle tracks will be done by wednesday the soonest, sunday the latest

**Comment by Aideryn** [comment]
^^^ Monster Specific Battle tracks, generic tracks are finished for the moment.

**Comment by Aideryn** [comment]
Track for Dialogue Scene

https://github.com/gmarino2048/AGD_Project/blob/master/Art/Sound/Getting%20to%20Know%20You.mp3

Track for Cooking Scene

https://github.com/gmarino2048/AGD_Project/blob/master/Art/Sound/Soulfood.mp3
