### ISSUE TITLE
UX/UI Edit -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#75]
Edit Scale of UX/UI for both Dialogue and Fight Scenes

Scale down and placement

Dialogue needs to be edited for 3 ~sentence long dialogue options rather than 6 buttons

**Comment by Farren183** [comment]
![mazur_dialogue_ui_art_2](https://user-images.githubusercontent.com/42968997/46016755-9b269780-c0a3-11e8-8639-4e3bd2026d40.png)
![mazur_battle_ui_art_2](https://user-images.githubusercontent.com/42968997/46016756-9b269780-c0a3-11e8-8e78-0a369adea0a5.png)
![mazur_battle_ui_2](https://user-images.githubusercontent.com/42968997/46016776-ada0d100-c0a3-11e8-8b84-e6542ebcf78f.png)
![mazur_battle_ui_2_guide](https://user-images.githubusercontent.com/42968997/46016777-ada0d100-c0a3-11e8-9aee-2527c81f7ac9.png)
![mazur_dialogue_ui_2](https://user-images.githubusercontent.com/42968997/46016778-ada0d100-c0a3-11e8-8328-9fdfcf5c9458.png)
![mazur_dialogue_ui_guide_2](https://user-images.githubusercontent.com/42968997/46016779-ada0d100-c0a3-11e8-825f-a7d1a7cf5dfb.png)
