### ISSUE TITLE
Minigame UI tutorials -- Bailey

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#89]
UI Icon tutorials for the minigames for next week. ICONS DUE THURSDAY MIDNIGHT

Microwave
-  Microwave timer (have with timer at 3, 2 and 1)
- Mouse Icon 
- (Ashli has the microwave asset)

Choping
- Show spacebar (pressed and unpressed)
- Knife Icon
- Cylinder  of some kind (uncut and cut)

Shake & Bake

- Shaker (w/o graphic)
- Mouse Icon (doesn't have to be different)

**Comment by Farren183** [comment]
https://github.com/gmarino2048/AGD_Project/issues/91

Here's a link to the tutorial animations which use the assets I've created
