### ISSUE TITLE
Minigame BG Renders -- Pam

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#90]
Finish up backgrounds for 

- Microwave Minigame
- Chopping Minigame
- Shake and Bake Minigame

Upload without placeholder assets.

**Comment by SmallestPamcakes** [comment]
![pizarro-ruiz_microwavebg_3](https://user-images.githubusercontent.com/42968970/46298521-45536300-c56d-11e8-8db1-04cced7f164f.png)

**Comment by SmallestPamcakes** [comment]
![pizarro-ruiz_cuttingboardbg_3](https://user-images.githubusercontent.com/42968970/46567397-62d35480-c900-11e8-9810-64211b1beb41.png)
![pizarro-ruiz_shakenbake_2](https://user-images.githubusercontent.com/42968970/46567399-69fa6280-c900-11e8-882b-e519c10f7896.png)
