### ISSUE TITLE
Tutorial Animations -- Ashli

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#91]
Create tutorial animations using UI Assets provided by Bailey. CANNOT BE STARTED UNTIL ICON ASSETS ARE UPLOADED.

Microwave
- Show timer going down
- At 1 second the mouse icon should move to click button and open microwave

Chopping
- Show Spacebar Icon going from unpressed to pressed
- Once pressed show knife moving down into cylindrical Asset
- Once knife moves up show asset chopped in half

Shake and Bake
- Show mouse going to click the Shaker
- Once clicked show both moving up and down at a increasing pace for about 2 seconds

**Comment by TheNamesAshli** [comment]
Tutorial Microwave (Separated for the time being.)
https://github.com/gmarino2048/AGD_Project/blob/Hudson_ANIMTutorial/Art/Animations/User_Files/Hudson_TUTMicroTimer.gif
https://github.com/gmarino2048/AGD_Project/blob/Hudson_ANIMTutorial/Art/Animations/User_Files/Hudson_TUTMicrowave.gif

Tutorial Shake
https://github.com/gmarino2048/AGD_Project/blob/Hudson_ANIMTutorial/Art/Animations/User_Files/Hudson_TUTShake.gif

Tutorial Chop
https://github.com/gmarino2048/AGD_Project/blob/Hudson_ANIMTutorial/Art/Animations/User_Files/Hudson_TUTChop.gif
