### ISSUE TITLE
Food Assets -- Khayree

### ISSUE THREAD

**Issue by Aideryn** [gmarino2048/AGD_Project#95]
Create assets for food for the following minigames

Microwave
- Can o Beans
- Canned Meat
- Algae Slime

Shake & Bake
- Aquarium Gravel
- Crushed Souls

Chopping
- Bones Chopped and unchopped and dusted 
- Peculiar Peppers chopped than unchopped mashed dusted

**Comment by Kaisif** [comment]
Food assets are still in (WIP) status only one is finished. Rest on the way.
